name: abies-linkage-transcriptome
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pyyaml
  - r-base=4.3
  - r-ggplot2
  - r-dplyr
  - r-pheatmap
  - r-qqman
  - r-wgcna
  - r-igraph
